### ISSUE TITLE
Opacity ?

### ISSUE THREAD

**Issue by justekoro** [tommyskeff/icue-controller#1]
Is there a way to power a led with a specific opacity ? (like, setting an rgba color)
Ex: `led.colour([255,75,21,150]) // 150 as the opacity`

**Comment by tommyskeff** [comment]
Thanks for the suggestion! I will work on adding RGBA functionality.

**Comment by tommyskeff** [comment]
I've implemented RGBA functionality where the alpha value is from 0 to 255 (0 being white and 255 being full brightness of colour). I hope you find this helpful.
